homeassistant:  # Name of the location where Home Assistant is running
  name: Valhalla 2
  # Location required to calculate the time the sun rises and sets
  latitude: 56.17506392
  longitude: 9.49150085
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 80
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Copenhagen
  # Customization file
  customize: !include customize.yaml

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  # Secrets are defined in the file secrets.yaml
   api_password: !secret http_password
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
   base_url: !secret base_url

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# Text to speech
tts:
  - platform: google

mqtt:
  broker: 192.168.1.100
  client_id: "home_assistant"

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml

sensor: !include sensors.yaml
 
duckdns:
  domain: "alsig"
  access_token: !secret duckdns_access_token

notify:
  - name: "pushBullet"
    platform: pushbullet
    api_key: !secret pushbullet_api_key


device_tracker:
#  - platform: netgear
#    host: !secret device_tracker_host
#    username: !secret device_tracker_user
#    password: !secret device_tracker_password
#    track_new_devices: no
  - platform: bluetooth_tracker
scene: 
  - name: Romantic
    entities:
      light.porch_strip:
        state: on
        rgb_color: [255, 0, 0]
  - name: Movies
    entities:
      light.porch_strip:
        state: on
        rgb_color: [0, 255, 0]

light:
  - platform: mqtt_json
    name: "Porch Strip"
    state_topic: "bruh/porch"
    command_topic: "bruh/porch/set"
    effect: true
    effect_list:
      - bpm
      - candy cane  
      - confetti  
      - cyclon rainbow  
      - dots  
      - fire  
      - glitter  
      - juggle  
      - lightning
      - noise  
      - police all  
      - police one  
      - rainbow  
      - rainbow with glitter  
      - ripple  
      - sinelon  
      - solid  
      - twinkle
      - sunrise  
    brightness: true
    flash: true
    rgb: true
    optimistic: false
    qos: 0

  - platform: mqtt
    name: "kitchenLight"
    state_topic: "stat/kitchenLight/POWER"
    command_topic: "cmnd/kitchenLight/POWER"
    availability_topic: "tele/kitchenLight/LWT"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    payload_available: "Online"
    payload_not_available: "Offline"
    retain: true

emulated_hue:
  exposed_domains:
    - light
    - scene

panel_iframe:
  configurator:
    title: 'Configurator'
    icon: mdi:wrench
    url: 'http://192.168.1.100:3218/'
