alias: 'Get Up'
trigger:
  platform: time
  at: "05:30:00"
condition:
  - condition: time
    weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
action:
  service: light.turn_on
  entity_id: light.bedroom3  
  data:  
    brightness: 127
    transition: 300