alias: 'Update Available Notifications'
trigger:
  platform: state
  entity_id: updater.updater
action:
  service: notify.pushbullet
  data:
    title: 'New version available'  
    message: 'Update for Home Assistant is available.'