alias: 'Turn off all lights when nobody is home'
trigger:
  platform: state
  entity_id: group.present
  from: 'home'
  to: 'not_home'
action:
  - service: light.turn_off
    entity_id: group.all_lights


